beginningSchedule: "Thu Aug 15 2024"
nbDaysForInput: 4

secrets:
  admins: [-123]
  modos: [-123]
  logFile: "/dev/null"

input: true
meta:
  nowShowShallowBunnyAd: false
  nowShowDataSourceAd: false
  nowShowSisyDuckAd: false
  nowTextAfterMap: ""
  nowTextWhenFinished: ""
  botUrl: ""
  aboutBigIcon: ""
  aboutShowShallowBunnyIcon: false
  aboutShowSisyDuckIcon: true
  nowMapImage: ""
  roomYouAreHereEmoticon: "ğŸ°"
  mobileAppName: ""
  prefix: "test"
  title: "test"

lineup:
  rooms:
    - "ğŸµ"
    - "ğŸ”¨"
  sets:
    "ğŸµ":
      - day: 1
        duration: 60
        dj: A
        hour: 1
        minute: 0
      - day: 1
        duration: 60
        dj: B
        hour: 2
        minute: 0
      - day: 1
        duration: 60
        dj: C
        hour: 3
        minute: 0
      - day: 1
        duration: 60
        dj: D
        hour: 4
        minute: 0
    "ğŸ”¨":
      - day: 1
        duration: 180
        dj: E
        hour: 3
        minute: 0
      - day: 1
        duration: 180
        dj: F
        hour: 6
        minute: 0
