secrets:
 modos: [ ]
 port: 8084

beginningSchedule: 'Fri Aug 16 2025'
botMotd: 'Hello, this is a demo bot.  Click one of the buttons below. If you type a room name, bunny will show its program. If you type something else, it will try to find sets matching that DJ.
'

meta:
 aboutBigIcon:  "demo-icon.jpg"
 aboutShowShallowBunnyIcon: true
 aboutShowSisyDuckIcon: true
 botUrl: "https://t.me/festivalDemoBot"
 nowMapImage: ""
 nowShowDataSourceAd: false
 nowShowShallowBunnyAd: false
 nowShowSisyDuckAd: false
 nowSubmitPR: ""
 nowTextAfterMap: "This is a demo festival"
 nowTextWhenFinished: "Demo finished"
 mobileAppName: "demo app"
 prefix: "demo"
 roomYouAreHereEmoticon: 'ğŸ°'
 title: "demo festival"

nbDaysForInput: 3

buttons: [ 'Now', 'ALL', 'Help' ]
input: false
nowSkipClosed: false


lineup:
    rooms:
        - "âŒ› Zeitmaschine"
        - "ğŸŒ¾ MÃ¼hle"
        - "ğŸ Turbo TÃ¼ff"
        - "ğŸ›µ Furore"
        - "ğŸ›º Rave Rikscha"
        - "ğŸ¤¡ Jesterfield"
    sets:
        "ğŸŒ¾ MÃ¼hle":
            - day: 0
              duration: 150
              dj: Fid Codo
              hour: 17
              minute: 0
            - day: 0
              duration: 120
              dj: Kotoe
              hour: 19
              minute: 30
            - day: 0
              duration: 120
              dj: Mwaah
              hour: 21
              minute: 30
            - day: 0
              duration: 120
              dj: Maka
              hour: 23
              minute: 30
            - day: 1
              duration: 120
              dj: Laberg
              hour: 1
              minute: 30
            - day: 1
              duration: 120
              dj: Luxon
              hour: 3
              minute: 30
            - day: 1
              duration: 120
              dj: Felidae
              hour: 12
              minute: 30
            - day: 1
              duration: 120
              dj: P
              hour: 14
              minute: 30
            - day: 1
              duration: 120
              dj: Julius Jung
              hour: 16
              minute: 30
            - day: 1
              duration: 120
              dj: Lisa Luka
              hour: 18
              minute: 30
            - day: 1
              duration: 120
              dj: Damon Jee
              hour: 20
              minute: 30
            - day: 1
              duration: 120
              dj: Diladi
              hour: 22
              minute: 30
            - day: 2
              duration: 120
              dj: Judith Van Waterkant
              hour: 0
              minute: 30
            - day: 2
              duration: 120
              dj: Isabeau Fort
              hour: 2
              minute: 30
            - day: 2
              duration: 120
              dj: Taotik Sayeth Disco
              hour: 4
              minute: 30
            - day: 2
              duration: 120
              dj: Onory
              hour: 6
              minute: 30
            - day: 2
              duration: 90
              dj: Lazy Hazy
              hour: 8
              minute: 30
            - day: 2
              duration: 120
              dj: Schwirri
              hour: 10
              minute: 0
            - day: 2
              duration: 120
              dj: C2C Aka Die Claras
              hour: 12
              minute: 0
            - day: 2
              duration: 120
              dj: Rosa Kante
              hour: 14
              minute: 0
            - day: 2
              duration: 120
              dj: Anna Almani
              hour: 16
              minute: 0
            - day: 2
              duration: 150
              dj: Melbo & Falke
              hour: 18
              minute: 0
            - day: 2
              duration: 120
              dj: Frieda Karlsson
              hour: 20
              minute: 30
            - day: 2
              duration: 90
              dj: Reyneke
              hour: 22
              minute: 30
            - day: 3
              duration: 120
              dj: KÃ¤ptn 12 & DÃ¼sen Trieb
              hour: 0
              minute: 0
            - day: 3
              duration: 120
              dj: Rufus Rabatz
              hour: 2
              minute: 0
            - day: 3
              duration: 120
              dj: Lisa Von Mond
              hour: 4
              minute: 0
            - day: 3
              duration: 120
              dj: SÃ¶rÃ¶s
              hour: 6
              minute: 0
            - day: 3
              duration: 120
              dj: Barti
              hour: 8
              minute: 0
            - day: 3
              duration: 120
              dj: Ella
              hour: 10
              minute: 0
            - day: 3
              duration: 120
              dj: Patte & Klatte
              hour: 12
              minute: 0
            - day: 3
              duration: 120
              dj: Marc Fuhrmann
              hour: 14
              minute: 0
            - day: 3
              duration: 120
              dj: Maria Die Ruhe
              hour: 16
              minute: 0
            - day: 3
              duration: 90
              dj: Deep Andi
              hour: 18
              minute: 0
            - day: 3
              duration: 150
              dj: Oberst & Buchner
              hour: 19
              minute: 30
        "ğŸ Turbo TÃ¼ff":
            - day: 0
              duration: 150
              dj: Maurin
              hour: 22
              minute: 0
            - day: 1
              duration: 120
              dj: Schmucko + Fate & Spinnebatz
              hour: 0
              minute: 30
            - day: 1
              duration: 120
              dj: Poloralph & Lutz Vuitton
              hour: 2
              minute: 30
            - day: 1
              duration: 120
              dj: Mango
              hour: 4
              minute: 30
            - day: 1
              duration: 150
              dj: Sire Jonah
              hour: 22
              minute: 0
            - day: 2
              duration: 120
              dj: Ben Derri
              hour: 0
              minute: 30
            - day: 2
              duration: 120
              dj: Choreophila
              hour: 2
              minute: 30
            - day: 2
              duration: 120
              dj: Hardschwoof 5000
              hour: 4
              minute: 30
            - day: 2
              duration: 120
              dj: Felgenteufel666
              hour: 6
              minute: 30
            - day: 2
              duration: 150
              dj: Hannah Hansen B2B DLZ
              hour: 22
              minute: 0
            - day: 3
              duration: 120
              dj: Zweistein
              hour: 0
              minute: 30
            - day: 3
              duration: 120
              dj: Melanchromie
              hour: 2
              minute: 30
            - day: 3
              duration: 120
              dj: TNT
              hour: 4
              minute: 30
            - day: 3
              duration: 120
              dj: Spicy Swelts
              hour: 6
              minute: 30
        "ğŸ›µ Furore":
            - day: 0
              duration: 120
              dj: Langschlenderer
              hour: 18
              minute: 30
            - day: 0
              duration: 120
              dj: Na Glaaaa... Das Songquiz
              hour: 20
              minute: 30
            - day: 0
              duration: 60
              dj: Kaos
              hour: 22
              minute: 30
            - day: 1
              duration: 60
              dj: Ende September
              hour: 0
              minute: 0
            - day: 1
              duration: 180
              dj: Queere MÃ¤rchenstunde + GrÃ¤fin Zobel Set
              hour: 14
              minute: 0
            - day: 1
              duration: 120
              dj: DJ Quien
              hour: 17
              minute: 0
            - day: 1
              duration: 60
              dj: Organi ???
              hour: 19
              minute: 0
            - day: 1
              duration: 120
              dj: Chaos Caraoke Club
              hour: 20
              minute: 30
            - day: 1
              duration: 60
              dj: Satisire
              hour: 23
              minute: 0
            - day: 2
              duration: 90
              dj: Gest
              hour: 0
              minute: 0
            - day: 2
              duration: 150
              dj: Re:Set
              hour: 1
              minute: 30
            - day: 2
              duration: 30
              dj: ???
              hour: 13
              minute: 30
            - day: 2
              duration: 150
              dj: Bingo Brudis
              hour: 14
              minute: 0
            - day: 2
              duration: 60
              dj: Rabayah
              hour: 17
              minute: 30
            - day: 2
              duration: 60
              dj: Mike Martin
              hour: 18
              minute: 30
            - day: 2
              duration: 90
              dj: The Razzones
              hour: 20
              minute: 0
            - day: 2
              duration: 90
              dj: Kite
              hour: 21
              minute: 30
            - day: 2
              duration: 90
              dj: Ugly-Dub
              hour: 23
              minute: 0
            - day: 3
              duration: 150
              dj: Matryoschka
              hour: 0
              minute: 30
            - day: 3
              duration: 120
              dj: Boba Ved
              hour: 3
              minute: 0
            - day: 3
              duration: 120
              dj: Hot Wlan (Calm)
              hour: 14
              minute: 0
            - day: 3
              duration: 60
              dj: The Dropdown Menu
              hour: 16
              minute: 30
            - day: 3
              duration: 90
              dj: Surprise
              hour: 17
              minute: 30
            - day: 3
              duration: 60
              dj: Rimojeki
              hour: 19
              minute: 30
        "ğŸ›º Rave Rikscha":
            - day: 0
              duration: 120
              dj: Simon Simono
              hour: 20
              minute: 0
            - day: 0
              duration: 120
              dj: Secret
              hour: 22
              minute: 0
            - day: 1
              duration: 120
              dj: Garnele
              hour: 11
              minute: 0
            - day: 1
              duration: 150
              dj: Zimt & Zucker
              hour: 13
              minute: 0
            - day: 1
              duration: 150
              dj: Lea Chuga
              hour: 15
              minute: 30
            - day: 1
              duration: 120
              dj: Wiebke
              hour: 18
              minute: 0
            - day: 1
              duration: 120
              dj: Pony-Barker
              hour: 20
              minute: 0
            - day: 2
              duration: 120
              dj: Kosh
              hour: 8
              minute: 0
            - day: 2
              duration: 120
              dj: Phillinger
              hour: 10
              minute: 0
            - day: 2
              duration: 120
              dj: Tones Mahones
              hour: 12
              minute: 0
            - day: 2
              duration: 120
              dj: Francesca B2B Maria Theresia Von Eberg
              hour: 14
              minute: 0
            - day: 2
              duration: 120
              dj: Tamtoomi
              hour: 16
              minute: 0
            - day: 2
              duration: 120
              dj: Okrim
              hour: 18
              minute: 0
            - day: 2
              duration: 120
              dj: Frequency w/ Haana Peony
              hour: 20
              minute: 0
            - day: 3
              duration: 150
              dj: Mella Mara
              hour: 8
              minute: 0
            - day: 3
              duration: 150
              dj: Anja Anique
              hour: 10
              minute: 30
            - day: 3
              duration: 120
              dj: Baerbel B2B Trauma Mia
              hour: 13
              minute: 0
            - day: 3
              duration: 120
              dj: Lisa Filou
              hour: 15
              minute: 0
            - day: 3
              duration: 120
              dj: Vacant
              hour: 17
              minute: 0
        "ğŸ¤¡ Jesterfield":
            - day: 1
              duration: 60
              dj: Malaika
              hour: 16
              minute: 0
            - day: 1
              duration: 60
              dj: Jawatnu
              hour: 17
              minute: 30
            - day: 1
              duration: 60
              dj: Sanes Medicine
              hour: 19
              minute: 0
            - day: 1
              duration: 60
              dj: Mosk P
              hour: 20
              minute: 30
            - day: 1
              duration: 60
              dj: Kristina Quarter
              hour: 22
              minute: 0
            - day: 1
              duration: 180
              dj: Jam Session
              hour: 23
              minute: 0
            - day: 2
              duration: 60
              dj: Atmo Sounds - Sera Lee
              hour: 13
              minute: 0
            - day: 2
              duration: 90
              dj: Ein Feld Voller Narren
              hour: 14
              minute: 0
            - day: 2
              duration: 30
              dj: Jack Jesterfield
              hour: 15
              minute: 30
            - day: 2
              duration: 60
              dj: Gouche Flustir
              hour: 16
              minute: 0
            - day: 2
              duration: 60
              dj: Theo Gillian & Sera Lee
              hour: 17
              minute: 0
            - day: 2
              duration: 90
              dj: Bunte Tute
              hour: 18
              minute: 0
            - day: 2
              duration: 30
              dj: Benjamin ???
              hour: 20
              minute: 0
            - day: 2
              duration: 60
              dj: Ora Blu
              hour: 21
              minute: 0
            - day: 2
              duration: 60
              dj: Sabraabb
              hour: 22
              minute: 30
            - day: 3
              duration: 180
              dj: Jam Session
              hour: 0
              minute: 30
            - day: 3
              duration: 90
              dj: Ein Feld Voller Narren
              hour: 14
              minute: 0
            - day: 3
              duration: 60
              dj: ???
              hour: 15
              minute: 30
            - day: 3
              duration: 300
              dj: Jamboree
              hour: 17
              minute: 0
        "âŒ› Zeitmaschine":
            - day: 1
              duration: 120
              dj: Marmori
              hour: 16
              minute: 0
            - day: 1
              duration: 120
              dj: Anice & Daniel Schumann
              hour: 18
              minute: 0
            - day: 1
              duration: 120
              dj: Sascha M & Munkler
              hour: 20
              minute: 0
            - day: 1
              duration: 90
              dj: Peter GroÃŸkreutz
              hour: 22
              minute: 0
            - day: 1
              duration: 120
              dj: Lotte Laut
              hour: 23
              minute: 30
            - day: 2
              duration: 120
              dj: Rad.lez
              hour: 1
              minute: 30
            - day: 2
              duration: 120
              dj: Yobovski
              hour: 3
              minute: 30
            - day: 2
              duration: 120
              dj: Phauna
              hour: 5
              minute: 30
            - day: 2
              duration: 150
              dj: Katzengold
              hour: 15
              minute: 0
            - day: 2
              duration: 120
              dj: Stan Starry & Mona Moore
              hour: 17
              minute: 30
            - day: 2
              duration: 120
              dj: Naicet & Elias Goldmund
              hour: 19
              minute: 30
            - day: 2
              duration: 120
              dj: Tom Baker
              hour: 21
              minute: 30
            - day: 2
              duration: 120
              dj: Aka Nina
              hour: 23
              minute: 30
            - day: 3
              duration: 120
              dj: Flanko
              hour: 1
              minute: 30
            - day: 3
              duration: 60
              dj: Fabian Laute
              hour: 3
              minute: 30
            - day: 3
              duration: 120
              dj: Empro
              hour: 4
              minute: 30
            - day: 3
              duration: 120
              dj: Tudse
              hour: 6
              minute: 30
            - day: 3
              duration: 120
              dj: Herr Zinnober
              hour: 13
              minute: 30
            - day: 3
              duration: 120
              dj: Intaktogene
              hour: 15
              minute: 30
            - day: 3
              duration: 120
              dj: Marco Liebreiz
              hour: 17
              minute: 30
            - day: 3
              duration: 90
              dj: Stimming
              hour: 19
              minute: 30
